using NUnit.Framework;

namespace Tests
{
    public class TestsCreatorTests
    {
        [Test]
        public void CreateTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}